export const API_CONFIG = {
  baseURL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001/api/v1",
  timeout: 30000,
  headers: {
    "Content-Type": "application/json",
  },
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    PROFILE: "/auth/profile",
    UPDATE_PROFILE: "/auth/profile",
    CHANGE_PASSWORD: "/auth/change-password",
  },
  BLOGS: {
    CREATE: "/blogs",
    LIST: "/blogs",
    GET_ONE: (id: string) => `/blogs/${id}`,
    GET_BY_SLUG: (slug: string) => `/blogs/slug/${slug}`,
    UPDATE: (id: string) => `/blogs/${id}`,
    DELETE: (id: string) => `/blogs/${id}`,
    PUBLISH: (id: string) => `/blogs/${id}/publish`,
    UNPUBLISH: (id: string) => `/blogs/${id}/unpublish`,
    LIKE: (id: string) => `/blogs/${id}/like`,
    MY_BLOGS: "/blogs/my-blogs",
    UPLOAD_IMAGE: "/blogs/images/upload",
    UPLOAD_IMAGES: "/blogs/images/upload-multiple",
  },
  API_KEYS: {
    CREATE: "/api-keys",
    LIST: "/api-keys",
    DELETE: (accessKeyId: string) => `/api-keys/${accessKeyId}`,
  },
  COMMENTS: {
    CREATE: "/comments",
    GET_ONE: (id: string) => `/comments/${id}`,
    GET_BY_BLOG: (blogId: string) => `/comments/blog/${blogId}`,
    GET_REPLIES: (commentId: string) => `/comments/${commentId}/replies`,
    UPDATE: (id: string) => `/comments/${id}`,
    DELETE: (id: string) => `/comments/${id}`,
    LIKE: (id: string) => `/comments/${id}/like`,
  },
  CATEGORIES: {
    CREATE: "/categories",
    LIST: "/categories",
    GET_ONE: (id: string) => `/categories/${id}`,
    UPDATE: (id: string) => `/categories/${id}`,
    DELETE: (id: string) => `/categories/${id}`,
  },
  SUBSCRIPTION: {
    GET: "/subscriptions",
    PLANS: "/subscriptions/plans",
    CHANGE_PLAN: "/subscriptions/change-plan",
    CANCEL: "/subscriptions/cancel",
  },
  BILLING: {
    INITIALIZE_CARD: "/billing/cards/initialize",
    CONFIRM_CARD: "/billing/cards/confirm",
    GET_CARDS: "/billing/cards",
    DELETE_CARD: (id: string) => `/billing/cards/${id}`,
    SET_DEFAULT_CARD: (id: string) => `/billing/cards/${id}/default`,
    GET_INVOICES: "/billing/invoices",
    GET_INVOICE: (id: string) => `/billing/invoices/${id}`,
  },
  ONBOARDING: {
    STATUS: "/onboarding/status",
    COMPLETE: "/onboarding/complete",
    SKIP: "/onboarding/skip",
  },
  SITES: {
    CREATE: "/sites",
    LIST: "/sites",
    GET_ONE: (id: string) => `/sites/${id}`,
    UPDATE: (id: string) => `/sites/${id}`,
    DELETE: (id: string) => `/sites/${id}`,
    GET_MEMBERS: (siteId: string) => `/sites/${siteId}/members`,
    ADD_MEMBER: (siteId: string) => `/sites/${siteId}/members`,
    UPDATE_MEMBER_ROLE: (siteId: string, userId: string) => `/sites/${siteId}/members/${userId}`,
    REMOVE_MEMBER: (siteId: string, userId: string) => `/sites/${siteId}/members/${userId}`,
    CREATE_INVITATION: (siteId: string) => `/sites/${siteId}/invitations`,
    GET_INVITATIONS: (siteId: string) => `/sites/${siteId}/invitations`,
  },
  INVITATIONS: {
    LIST: "/invitations",
    ACCEPT: (token: string) => `/invitations/${token}/accept`,
    REJECT: (token: string) => `/invitations/${token}/reject`,
  },
};

export const QUERY_KEYS = {
  AUTH_USER: ["auth", "user"],
  BLOGS: ["blogs"],
  BLOG: (id: string) => ["blogs", id],
  MY_BLOGS: ["blogs", "my-blogs"],
  API_KEYS: ["api-keys"],
  COMMENTS: ["comments"],
  COMMENTS_BY_BLOG: (blogId: string) => ["comments", "blog", blogId],
  COMMENT_REPLIES: (commentId: string) => ["comments", commentId, "replies"],
  CATEGORIES: ["categories"],
  SUBSCRIPTION: ["subscription"],
  PLANS: ["subscription", "plans"],
  BILLING_CARDS: ["billing", "cards"],
  BILLING_INVOICES: ["billing", "invoices"],
  SITES: ["sites"],
  SITE: (id: string) => ["sites", id],
  SITE_MEMBERS: (siteId: string) => ["sites", siteId, "members"],
  SITE_INVITATIONS: (siteId: string) => ["sites", siteId, "invitations"],
  USER_INVITATIONS: ["invitations"],
};

