export const API_CONFIG = {
  baseURL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001/api/v1",
  timeout: 30000,
  headers: {
    "Content-Type": "application/json",
  },
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    SIGNUP: "/auth/signup",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    PROFILE: "/auth/profile",
    UPDATE_PROFILE: "/auth/profile",
    CHANGE_PASSWORD: "/auth/change-password",
    UPDATE_SITE_CONTEXT: "/auth/site-context",
  },
  BLOGS: {
    CREATE: (siteId: string) => `/sites/${siteId}/blogs`,
    LIST: (siteId: string) => `/sites/${siteId}/blogs`,
    GET_ONE: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}`,
    GET_BY_SLUG: (siteId: string, slug: string) => `/sites/${siteId}/blogs/slug/${slug}`,
    UPDATE: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}`,
    DELETE: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}`,
    PUBLISH: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}/publish`,
    UNPUBLISH: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}/unpublish`,
    LIKE: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}/like`,
    MY_BLOGS: (siteId: string) => `/sites/${siteId}/blogs/my-blogs`,
    UPLOAD_IMAGE: (siteId: string) => `/sites/${siteId}/blogs/images/upload`,
    UPLOAD_IMAGES: (siteId: string) => `/sites/${siteId}/blogs/images/upload-multiple`,
    REVIEW: (siteId: string, blogId?: string) =>
      blogId ? `/sites/${siteId}/blogs/${blogId}/review` : `/sites/${siteId}/blogs/review`,
    APPLY_REVIEW: (siteId: string, blogId: string) => `/sites/${siteId}/blogs/${blogId}/review/apply`,
    APPLY_ONE: (siteId: string, blogId: string) => `/sites/${siteId}/blogs/${blogId}/review/apply-one`,
    RESTORE_VERSION: (siteId: string, blogId: string, version: number) =>
      `/sites/${siteId}/blogs/${blogId}/restore/${version}`,
    GENERATE_ANALYZE: (siteId: string) => `/sites/${siteId}/blogs/generate/analyze`,
    GENERATE: (siteId: string) => `/sites/${siteId}/blogs/generate`,
    SCHEDULE: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}/schedule`,
    GET_SCHEDULE: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}/schedule`,
    UNSCHEDULE: (siteId: string, id: string) => `/sites/${siteId}/blogs/${id}/schedule`,
  },
  COMMENTS: {
    CREATE: "/comments",
    GET_ONE: (id: string) => `/comments/${id}`,
    GET_BY_BLOG: (blogId: string) => `/comments/blog/${blogId}`,
    GET_REPLIES: (commentId: string) => `/comments/${commentId}/replies`,
    UPDATE: (id: string) => `/comments/${id}`,
    DELETE: (id: string) => `/comments/${id}`,
    LIKE: (id: string) => `/comments/${id}/like`,
  },
  CATEGORIES: {
    CREATE: (siteId: string) => `/sites/${siteId}/categories`,
    LIST: (siteId: string) => `/sites/${siteId}/categories`,
    GET_ONE: (siteId: string, id: string) => `/sites/${siteId}/categories/${id}`,
    UPDATE: (siteId: string, id: string) => `/sites/${siteId}/categories/${id}`,
    DELETE: (siteId: string, id: string) => `/sites/${siteId}/categories/${id}`,
    IMPORT: (siteId: string) => `/sites/${siteId}/categories/import`,
  },
  SUBSCRIPTION: {
    GET: "/subscriptions",
    PLANS: "/subscriptions/plans",
    CHANGE_PLAN: "/subscriptions/change-plan",
    CANCEL: "/subscriptions/cancel",
  },
  BILLING: {
    INITIALIZE_CARD: "/billing/cards/initialize",
    CONFIRM_CARD: "/billing/cards/confirm",
    GET_CARDS: "/billing/cards",
    DELETE_CARD: (id: string) => `/billing/cards/${id}`,
    SET_DEFAULT_CARD: (id: string) => `/billing/cards/${id}/default`,
    GET_INVOICES: "/billing/invoices",
    GET_INVOICE: (id: string) => `/billing/invoices/${id}`,
  },
  ONBOARDING: {
    STATUS: "/onboarding/status",
    COMPLETE: "/onboarding/complete",
    SKIP: "/onboarding/skip",
  },
  SITES: {
    CREATE: "/sites",
    ENSURE_DEFAULT: "/sites/ensure-default",
    LIST: "/sites",
    GET_ONE: (id: string) => `/sites/${id}`,
    UPDATE: (id: string) => `/sites/${id}`,
    DELETE: (id: string) => `/sites/${id}`,
    GET_MEMBERS: (siteId: string) => `/sites/${siteId}/members`,
    ADD_MEMBER: (siteId: string) => `/sites/${siteId}/members`,
    UPDATE_MEMBER_ROLE: (siteId: string, userId: string) => `/sites/${siteId}/members/${userId}`,
    REMOVE_MEMBER: (siteId: string, userId: string) => `/sites/${siteId}/members/${userId}`,
    CREATE_INVITATION: (siteId: string) => `/sites/${siteId}/invitations`,
    GET_INVITATIONS: (siteId: string) => `/sites/${siteId}/invitations`,
    CANCEL_INVITATION: (siteId: string, invitationId: string) => `/sites/${siteId}/invitations/${invitationId}`,
    LIST_API_KEYS: (siteId: string) => `/sites/${siteId}/api-keys`,
    CREATE_API_KEY: (siteId: string) => `/sites/${siteId}/api-keys`,
    DELETE_API_KEY: (siteId: string, accessKeyId: string) => `/sites/${siteId}/api-keys/${accessKeyId}`,
  },
  INVITATIONS: {
    LIST: "/invitations",
    ACCEPT: (token: string) => `/invitations/${token}/accept`,
    REJECT: (token: string) => `/invitations/${token}/reject`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    UNREAD_COUNT: "/notifications/unread-count",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
  CAMPAIGNS: {
    CREATE: (siteId: string) => `/sites/${siteId}/campaigns`,
    LIST: (siteId: string) => `/sites/${siteId}/campaigns`,
    MY_CAMPAIGNS: (siteId: string) => `/sites/${siteId}/campaigns/my-campaigns`,
    GET_ONE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/${id}`,
    GET_STATS: (siteId: string, id: string) => `/sites/${siteId}/campaigns/${id}/stats`,
    UPDATE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/${id}`,
    DELETE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/${id}`,
    ACTIVATE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/${id}/activate`,
    PAUSE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/${id}/pause`,
    CANCEL: (siteId: string, id: string) => `/sites/${siteId}/campaigns/${id}/cancel`,
    DATE_RANGE: (siteId: string) => `/sites/${siteId}/campaigns/date-range`,
    SCHEDULED_POSTS: {
      CREATE: (siteId: string) => `/sites/${siteId}/campaigns/scheduled-posts`,
      LIST: (siteId: string) => `/sites/${siteId}/campaigns/scheduled-posts`,
      MY_POSTS: (siteId: string) => `/sites/${siteId}/campaigns/scheduled-posts/my-posts`,
      GET_ONE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/scheduled-posts/${id}`,
      UPDATE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/scheduled-posts/${id}`,
      DELETE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/scheduled-posts/${id}`,
      CANCEL: (siteId: string, id: string) => `/sites/${siteId}/campaigns/scheduled-posts/${id}/cancel`,
      MOVE_TO_CAMPAIGN: (siteId: string, id: string) =>
        `/sites/${siteId}/campaigns/scheduled-posts/${id}/move-to-campaign`,
      REMOVE_FROM_CAMPAIGN: (siteId: string, id: string) =>
        `/sites/${siteId}/campaigns/scheduled-posts/${id}/remove-from-campaign`,
      DATE_RANGE: (siteId: string) => `/sites/${siteId}/campaigns/scheduled-posts/date-range`,
    },
    TEMPLATES: {
      LIST: (siteId: string) => `/sites/${siteId}/campaigns/templates`,
      GET_ONE: (siteId: string, id: string) => `/sites/${siteId}/campaigns/templates/${id}`,
      GET_BY_TYPE: (siteId: string, type: string) => `/sites/${siteId}/campaigns/templates/type/${type}`,
    },
    AGENT_CHAT: (siteId: string) => `/sites/${siteId}/campaigns/agent/chat`,
    AGENT_CREATE_FROM_PROPOSAL: (siteId: string) => `/sites/${siteId}/campaigns/agent/create-from-proposal`,
  },
};

export const QUERY_KEYS = {
  AUTH_USER: ["auth", "user"],
  BLOGS: ["blogs"],
  BLOG: (id: string) => ["blogs", id],
  MY_BLOGS: ["blogs", "my-blogs"],
  API_KEYS: (siteId: string) => ["api-keys", siteId],
  COMMENTS: ["comments"],
  COMMENTS_BY_BLOG: (blogId: string) => ["comments", "blog", blogId],
  COMMENT_REPLIES: (commentId: string) => ["comments", commentId, "replies"],
  CATEGORIES: ["categories"],
  SUBSCRIPTION: ["subscription"],
  PLANS: ["subscription", "plans"],
  BILLING_CARDS: ["billing", "cards"],
  BILLING_INVOICES: ["billing", "invoices"],
  SITES: ["sites"],
  SITE: (id: string) => ["sites", id],
  SITE_MEMBERS: (siteId: string) => ["sites", siteId, "members"],
  SITE_INVITATIONS: (siteId: string) => ["sites", siteId, "invitations"],
  USER_INVITATIONS: ["invitations"],
  NOTIFICATIONS: ["notifications"],
  NOTIFICATIONS_UNREAD_COUNT: ["notifications", "unread-count"],
  CAMPAIGNS: ["campaigns"],
  CAMPAIGN: (id: string) => ["campaigns", id],
  MY_CAMPAIGNS: ["campaigns", "my-campaigns"],
  SCHEDULED_POSTS: ["scheduled-posts"],
  SCHEDULED_POST: (id: string) => ["scheduled-posts", id],
  MY_SCHEDULED_POSTS: ["scheduled-posts", "my-posts"],
  CAMPAIGN_TEMPLATES: ["campaign-templates"],
};

